import { DayPlan, WorkoutDay, ShoppingItem, Momento } from "./types";

// Plan orientativo ~2150-2250 kcal / ~180-190 g proteína al día (referencia
// para una persona activa en fase de definición, aprox. 80-90 kg). Ajusta
// raciones al alza o a la baja según el objetivo calculado en "Perfil".

export const MOMENTO_INFO: Record<Momento, { label: string; emoji: string }> = {
  desayuno: { label: "Desayuno", emoji: "🍳" },
  media_manana: { label: "Media mañana", emoji: "🥤" },
  comida: { label: "Comida", emoji: "🍗" },
  merienda: { label: "Merienda", emoji: "🍓" },
  cena: { label: "Cena", emoji: "🌙" },
  libre: { label: "Libre", emoji: "🎉" },
};

export const MEAL_PLAN: DayPlan[] = [
  {
    day: "lunes",
    entreno: true,
    diaLibreDieta: false,
    meals: [
      {
        id: "lun-desayuno",
        nombre: "Tortilla de claras + avena",
        kcal: 420,
        proteina: 38,
        ingredientes: ["huevos", "claras de huevo pasteurizadas", "espinacas", "avena", "canela"],
        momento: "desayuno",
      },
      {
        id: "lun-media",
        nombre: "Batido de proteína con plátano",
        kcal: 280,
        proteina: 33,
        ingredientes: ["proteína whey", "leche desnatada", "plátano"],
        momento: "media_manana",
      },
      {
        id: "lun-comida",
        nombre: "Pollo a la plancha, arroz integral y brócoli",
        kcal: 650,
        proteina: 55,
        ingredientes: ["pechuga de pollo", "arroz integral", "brócoli", "aceite de oliva"],
        momento: "comida",
      },
      {
        id: "lun-merienda",
        nombre: "Yogur griego 0% con nueces y miel",
        kcal: 250,
        proteina: 20,
        ingredientes: ["yogur griego 0%", "nueces", "miel"],
        momento: "merienda",
      },
      {
        id: "lun-cena",
        nombre: "Salmón al horno con boniato y ensalada",
        kcal: 550,
        proteina: 40,
        ingredientes: ["salmón", "boniato", "lechuga", "tomate"],
        momento: "cena",
      },
    ],
  },
  {
    day: "martes",
    entreno: true,
    diaLibreDieta: false,
    meals: [
      {
        id: "mar-desayuno",
        nombre: "Porridge de avena con proteína y arándanos",
        kcal: 430,
        proteina: 36,
        ingredientes: ["avena", "proteína whey", "arándanos", "almendras"],
        momento: "desayuno",
      },
      {
        id: "mar-media",
        nombre: "2 huevos duros + fruta",
        kcal: 260,
        proteina: 18,
        ingredientes: ["huevos", "manzana"],
        momento: "media_manana",
      },
      {
        id: "mar-comida",
        nombre: "Ternera salteada con quinoa y pimientos",
        kcal: 640,
        proteina: 52,
        ingredientes: ["ternera magra", "quinoa", "pimiento", "cebolla", "aceite de oliva"],
        momento: "comida",
      },
      {
        id: "mar-merienda",
        nombre: "Batido de proteína con crema de cacahuete",
        kcal: 300,
        proteina: 32,
        ingredientes: ["proteína whey", "leche de almendras", "crema de cacahuete"],
        momento: "merienda",
      },
      {
        id: "mar-cena",
        nombre: "Tortilla de claras con atún y espárragos",
        kcal: 480,
        proteina: 48,
        ingredientes: ["claras de huevo pasteurizadas", "atún al natural", "espárragos", "pan integral"],
        momento: "cena",
      },
    ],
  },
  {
    day: "miercoles",
    entreno: false,
    diaLibreDieta: false,
    meals: [
      {
        id: "mie-desayuno",
        nombre: "Skyr con muesli sin azúcar y fresas",
        kcal: 380,
        proteina: 30,
        ingredientes: ["skyr o queso batido 0%", "muesli sin azúcar", "fresas"],
        momento: "desayuno",
      },
      {
        id: "mie-media",
        nombre: "Batido de proteína con frutos secos",
        kcal: 300,
        proteina: 30,
        ingredientes: ["proteína whey", "leche desnatada", "almendras"],
        momento: "media_manana",
      },
      {
        id: "mie-comida",
        nombre: "Merluza a la plancha, patata y judías verdes",
        kcal: 560,
        proteina: 45,
        ingredientes: ["merluza", "patata", "judías verdes", "aceite de oliva"],
        momento: "comida",
      },
      {
        id: "mie-merienda",
        nombre: "Requesón con canela y nueces",
        kcal: 220,
        proteina: 22,
        ingredientes: ["requesón", "canela", "nueces"],
        momento: "merienda",
      },
      {
        id: "mie-cena",
        nombre: "Pavo a la plancha con crema de calabacín",
        kcal: 460,
        proteina: 42,
        ingredientes: ["pechuga de pavo", "calabacín", "cebolla", "lechuga", "tomate"],
        momento: "cena",
      },
    ],
  },
  {
    day: "jueves",
    entreno: true,
    diaLibreDieta: false,
    meals: [
      {
        id: "jue-desayuno",
        nombre: "Tortilla francesa con aguacate y pan integral",
        kcal: 440,
        proteina: 32,
        ingredientes: ["huevos", "claras de huevo pasteurizadas", "aguacate", "pan integral"],
        momento: "desayuno",
      },
      {
        id: "jue-media",
        nombre: "Batido de proteína con plátano",
        kcal: 280,
        proteina: 33,
        ingredientes: ["proteína whey", "leche desnatada", "plátano"],
        momento: "media_manana",
      },
      {
        id: "jue-comida",
        nombre: "Pollo al curry con arroz basmati y verduras",
        kcal: 660,
        proteina: 54,
        ingredientes: ["pechuga de pollo", "arroz basmati", "pimiento", "cebolla", "curry"],
        momento: "comida",
      },
      {
        id: "jue-merienda",
        nombre: "Yogur griego con proteína y canela",
        kcal: 260,
        proteina: 28,
        ingredientes: ["yogur griego 0%", "proteína whey", "canela"],
        momento: "merienda",
      },
      {
        id: "jue-cena",
        nombre: "Solomillo de cerdo con puré de coliflor",
        kcal: 520,
        proteina: 46,
        ingredientes: ["solomillo de cerdo", "coliflor", "aceite de oliva"],
        momento: "cena",
      },
    ],
  },
  {
    day: "viernes",
    entreno: true,
    diaLibreDieta: false,
    meals: [
      {
        id: "vie-desayuno",
        nombre: "Avena con proteína, cacao puro y plátano",
        kcal: 430,
        proteina: 36,
        ingredientes: ["avena", "proteína whey", "cacao puro", "plátano"],
        momento: "desayuno",
      },
      {
        id: "vie-media",
        nombre: "2 huevos duros + tomate",
        kcal: 220,
        proteina: 16,
        ingredientes: ["huevos", "tomate"],
        momento: "media_manana",
      },
      {
        id: "vie-comida",
        nombre: "Salmón al horno con arroz integral y espárragos",
        kcal: 640,
        proteina: 48,
        ingredientes: ["salmón", "arroz integral", "espárragos"],
        momento: "comida",
      },
      {
        id: "vie-merienda",
        nombre: "Batido de proteína con leche desnatada",
        kcal: 260,
        proteina: 32,
        ingredientes: ["proteína whey", "leche desnatada"],
        momento: "merienda",
      },
      {
        id: "vie-cena",
        nombre: "Pollo a la plancha con ensalada de garbanzos",
        kcal: 540,
        proteina: 46,
        ingredientes: ["pechuga de pollo", "garbanzos cocidos", "lechuga", "tomate", "aceite de oliva"],
        momento: "cena",
      },
    ],
  },
  {
    day: "sabado",
    entreno: false,
    diaLibreDieta: false,
    meals: [
      {
        id: "sab-desayuno",
        nombre: "Tostadas integrales con huevos revueltos y aguacate",
        kcal: 460,
        proteina: 30,
        ingredientes: ["pan integral", "huevos", "aguacate"],
        momento: "desayuno",
      },
      {
        id: "sab-media",
        nombre: "Batido de proteína con fruta",
        kcal: 280,
        proteina: 32,
        ingredientes: ["proteína whey", "leche desnatada", "manzana"],
        momento: "media_manana",
      },
      {
        id: "sab-comida",
        nombre: "Pasta integral con atún, tomate y queso fresco batido",
        kcal: 620,
        proteina: 44,
        ingredientes: ["pasta integral", "atún al natural", "tomate", "queso fresco batido 0%"],
        momento: "comida",
      },
      {
        id: "sab-merienda",
        nombre: "Yogur griego con miel y nueces",
        kcal: 250,
        proteina: 20,
        ingredientes: ["yogur griego 0%", "miel", "nueces"],
        momento: "merienda",
      },
      {
        id: "sab-cena",
        nombre: "Tortilla de patata ligera y ensalada",
        kcal: 480,
        proteina: 30,
        ingredientes: ["huevos", "patata", "cebolla", "lechuga", "tomate"],
        momento: "cena",
      },
    ],
  },
  {
    day: "domingo",
    entreno: false,
    diaLibreDieta: true,
    meals: [
      {
        id: "dom-desayuno",
        nombre: "Desayuno proteico habitual (mantén esta comida fija)",
        kcal: 420,
        proteina: 35,
        ingredientes: ["huevos", "avena", "proteína whey"],
        momento: "desayuno",
      },
      {
        id: "dom-libre",
        nombre: "Comidas libres del día — disfruta sin contar de forma estricta",
        kcal: 0,
        proteina: 0,
        ingredientes: [],
        momento: "libre",
      },
    ],
  },
];

export const WORKOUT_PLAN: WorkoutDay[] = [
  {
    day: "lunes",
    titulo: "Empuje — pecho, hombro, tríceps",
    ejercicios: [
      {
        id: "lun-1",
        nombre: "Press banca (barra o mancuernas)",
        pauta: "4 x 8-10",
        emoji: "🏋️",
        comoHacerlo: "Espalda pegada al banco, baja la barra controlada hasta rozar el pecho y empuja sin bloquear los codos de golpe.",
      },
      {
        id: "lun-2",
        nombre: "Press militar con mancuernas",
        pauta: "3 x 10",
        emoji: "💪",
        comoHacerlo: "De pie o sentado, empuja las mancuernas hacia arriba sin arquear la espalda, codos ligeramente por delante del cuerpo.",
      },
      {
        id: "lun-3",
        nombre: "Fondos en paralelas o press inclinado",
        pauta: "3 x 10-12",
        emoji: "🤸",
        comoHacerlo: "Baja hasta que los hombros queden a la altura de los codos, manteniendo el torso ligeramente inclinado hacia delante.",
      },
      {
        id: "lun-4",
        nombre: "Elevaciones laterales",
        pauta: "3 x 15",
        emoji: "🙆",
        comoHacerlo: "Sube los brazos ligeramente flexionados hasta la altura del hombro, sin impulso, controlando la bajada.",
      },
      {
        id: "lun-5",
        nombre: "Extensión de tríceps en polea",
        pauta: "3 x 12",
        emoji: "🦾",
        comoHacerlo: "Codos pegados al cuerpo, extiende hacia abajo solo con el antebrazo, sin mover el hombro.",
      },
      {
        id: "lun-6",
        nombre: "Plancha abdominal",
        pauta: "3 x 40 seg",
        emoji: "🧘",
        comoHacerlo: "Cuerpo en línea recta de cabeza a talones, abdomen apretado, sin dejar caer la cadera.",
      },
    ],
  },
  {
    day: "martes",
    titulo: "Tirón — espalda, bíceps",
    ejercicios: [
      {
        id: "mar-1",
        nombre: "Dominadas o jalón al pecho",
        pauta: "4 x 8-10",
        emoji: "🧗",
        comoHacerlo: "Tira llevando el pecho hacia la barra, juntando los omóplatos, y baja controlando hasta extender casi del todo.",
      },
      {
        id: "mar-2",
        nombre: "Remo con barra o mancuerna",
        pauta: "4 x 10",
        emoji: "🚣",
        comoHacerlo: "Espalda recta e inclinada hacia delante, tira del peso hacia el abdomen apretando la espalda arriba.",
      },
      {
        id: "mar-3",
        nombre: "Remo en polea baja",
        pauta: "3 x 12",
        emoji: "🎣",
        comoHacerlo: "Tira con la espalda, no con los brazos: lleva los codos atrás y junta los omóplatos al final del movimiento.",
      },
      {
        id: "mar-4",
        nombre: "Curl de bíceps con barra",
        pauta: "3 x 12",
        emoji: "💪",
        comoHacerlo: "Codos fijos pegados al torso, sube el peso solo flexionando el codo, sin balancear el cuerpo.",
      },
      {
        id: "mar-5",
        nombre: "Face pull",
        pauta: "3 x 15",
        emoji: "🎯",
        comoHacerlo: "Tira de la cuerda hacia la cara separando las manos, codos altos, apretando la parte trasera del hombro.",
      },
      {
        id: "mar-6",
        nombre: "Elevación de piernas colgado / crunch",
        pauta: "3 x 15",
        emoji: "🌀",
        comoHacerlo: "Sube las piernas con control usando el abdomen, evitando balancearte con el impulso.",
      },
    ],
  },
  {
    day: "jueves",
    titulo: "Piernas",
    ejercicios: [
      {
        id: "jue-1",
        nombre: "Sentadilla con barra",
        pauta: "4 x 8-10",
        emoji: "🏋️",
        comoHacerlo: "Baja como si te sentaras, rodillas en línea con los pies, pecho arriba, hasta que las caderas bajen de las rodillas.",
      },
      {
        id: "jue-2",
        nombre: "Peso muerto rumano",
        pauta: "3 x 10",
        emoji: "🏋️‍♂️",
        comoHacerlo: "Piernas casi rectas, baja la barra pegada a las piernas empujando la cadera hacia atrás, espalda siempre recta.",
      },
      {
        id: "jue-3",
        nombre: "Zancadas con mancuernas",
        pauta: "3 x 12 por pierna",
        emoji: "🚶",
        comoHacerlo: "Da un paso largo y baja hasta que ambas rodillas queden casi a 90°, sin que la rodilla delantera sobrepase el pie.",
      },
      {
        id: "jue-4",
        nombre: "Prensa de piernas",
        pauta: "3 x 12",
        emoji: "🦵",
        comoHacerlo: "Baja controlado hasta 90° de rodilla, sin despegar la zona lumbar del respaldo.",
      },
      {
        id: "jue-5",
        nombre: "Elevación de talones (gemelos)",
        pauta: "4 x 15",
        emoji: "🦶",
        comoHacerlo: "Sube todo lo que puedas sobre la punta del pie y baja despacio estirando bien el gemelo.",
      },
      {
        id: "jue-6",
        nombre: "Plancha lateral",
        pauta: "3 x 30 seg por lado",
        emoji: "🧘",
        comoHacerlo: "Cuerpo en línea recta apoyado en el antebrazo, cadera elevada sin caer, abdomen apretado.",
      },
    ],
  },
  {
    day: "viernes",
    titulo: "Full body + definición",
    ejercicios: [
      {
        id: "vie-1",
        nombre: "Peso muerto convencional (carga moderada)",
        pauta: "3 x 8",
        emoji: "🏋️‍♂️",
        comoHacerlo: "Barra pegada a las espinillas, espalda recta, empuja el suelo con los pies para levantarte, cadera y hombros a la vez.",
      },
      {
        id: "vie-2",
        nombre: "Press banca inclinado con mancuernas",
        pauta: "3 x 10",
        emoji: "🏋️",
        comoHacerlo: "Banco a 30-45°, baja las mancuernas a la altura del pecho superior y empuja sin chocarlas arriba.",
      },
      {
        id: "vie-3",
        nombre: "Remo con mancuerna a una mano",
        pauta: "3 x 10",
        emoji: "🚣",
        comoHacerlo: "Apoya una mano y rodilla en el banco, tira de la mancuerna hacia la cadera manteniendo la espalda recta.",
      },
      {
        id: "vie-4",
        nombre: "Sentadilla goblet",
        pauta: "3 x 12",
        emoji: "🏋️",
        comoHacerlo: "Sujeta el peso pegado al pecho y baja manteniendo el torso vertical y los codos entre las rodillas.",
      },
      {
        id: "vie-5",
        nombre: "Circuito metabólico (burpees, mountain climbers, kettlebell swings)",
        pauta: "3 rondas x 40s/20s",
        emoji: "🔥",
        comoHacerlo: "Encadena los tres ejercicios a ritmo alto durante 40 segundos, descansa 20 y repite. Prioriza la técnica antes que la velocidad.",
      },
      {
        id: "vie-6",
        nombre: "Plancha + rotaciones rusas",
        pauta: "3 x 15",
        emoji: "🌀",
        comoHacerlo: "Tras la plancha, siéntate con rodillas flexionadas y gira el torso de lado a lado sin dejar caer la espalda.",
      },
    ],
  },
];

export const SHOPPING_CATEGORIES = [
  "Proteínas",
  "Lácteos",
  "Carbohidratos",
  "Verduras y fruta",
  "Frutos secos y grasas",
  "Suplementos",
  "Otros",
];

export const CATEGORY_EMOJI: Record<string, string> = {
  "Proteínas": "🍗",
  "Lácteos": "🥛",
  "Carbohidratos": "🌾",
  "Verduras y fruta": "🥦",
  "Frutos secos y grasas": "🥜",
  "Suplementos": "💊",
  "Otros": "🧂",
};

function item(id: string, nombre: string, categoria: string): ShoppingItem {
  return { id, nombre, categoria, base: true };
}

export const BASE_SHOPPING_LIST: ShoppingItem[] = [
  item("p-pollo", "Pechuga de pollo", "Proteínas"),
  item("p-pavo", "Pechuga de pavo", "Proteínas"),
  item("p-ternera", "Ternera magra", "Proteínas"),
  item("p-cerdo", "Solomillo de cerdo", "Proteínas"),
  item("p-salmon", "Salmón", "Proteínas"),
  item("p-merluza", "Merluza", "Proteínas"),
  item("p-atun", "Atún al natural (lata)", "Proteínas"),
  item("p-huevos", "Huevos", "Proteínas"),
  item("p-claras", "Claras de huevo pasteurizadas", "Proteínas"),
  item("l-yogur", "Yogur griego 0%", "Lácteos"),
  item("l-skyr", "Skyr o queso batido 0%", "Lácteos"),
  item("l-requeson", "Requesón", "Lácteos"),
  item("l-leche", "Leche desnatada", "Lácteos"),
  item("l-quesofresco", "Queso fresco batido 0%", "Lácteos"),
  item("c-avena", "Avena", "Carbohidratos"),
  item("c-arrozintegral", "Arroz integral", "Carbohidratos"),
  item("c-arrozbasmati", "Arroz basmati", "Carbohidratos"),
  item("c-quinoa", "Quinoa", "Carbohidratos"),
  item("c-patata", "Patata", "Carbohidratos"),
  item("c-boniato", "Boniato", "Carbohidratos"),
  item("c-panintegral", "Pan integral", "Carbohidratos"),
  item("c-pastaintegral", "Pasta integral", "Carbohidratos"),
  item("c-muesli", "Muesli sin azúcar", "Carbohidratos"),
  item("v-espinacas", "Espinacas", "Verduras y fruta"),
  item("v-brocoli", "Brócoli", "Verduras y fruta"),
  item("v-pimiento", "Pimiento", "Verduras y fruta"),
  item("v-cebolla", "Cebolla", "Verduras y fruta"),
  item("v-esparragos", "Espárragos", "Verduras y fruta"),
  item("v-calabacin", "Calabacín", "Verduras y fruta"),
  item("v-judiasverdes", "Judías verdes", "Verduras y fruta"),
  item("v-coliflor", "Coliflor", "Verduras y fruta"),
  item("v-tomate", "Tomate", "Verduras y fruta"),
  item("v-lechuga", "Lechuga", "Verduras y fruta"),
  item("v-aguacate", "Aguacate", "Verduras y fruta"),
  item("v-platano", "Plátano", "Verduras y fruta"),
  item("v-arandanos", "Arándanos", "Verduras y fruta"),
  item("v-fresas", "Fresas", "Verduras y fruta"),
  item("v-manzana", "Manzana", "Verduras y fruta"),
  item("v-garbanzos", "Garbanzos cocidos", "Verduras y fruta"),
  item("f-nueces", "Nueces", "Frutos secos y grasas"),
  item("f-almendras", "Almendras", "Frutos secos y grasas"),
  item("f-cacahuete", "Crema de cacahuete 100%", "Frutos secos y grasas"),
  item("f-aceite", "Aceite de oliva virgen extra", "Frutos secos y grasas"),
  item("s-whey", "Proteína whey", "Suplementos"),
  item("s-creatina", "Creatina monohidrato", "Suplementos"),
  item("s-betaalanina", "Beta-alanina", "Suplementos"),
  item("o-miel", "Miel", "Otros"),
  item("o-canela", "Canela", "Otros"),
  item("o-cacao", "Cacao puro en polvo", "Otros"),
  item("o-curry", "Curry en polvo", "Otros"),
];
