import { DayPlan, WorkoutDay, ShoppingItem, Momento } from "./types";

// Plan orientativo ~1970-2150 kcal / ~180-190 g proteína al día (referencia
// para una persona activa en fase de definición, aprox. 80-90 kg). Ajusta
// raciones al alza o a la baja según el objetivo calculado en "Perfil".

export const MOMENTO_INFO: Record<Momento, { label: string; emoji: string }> = {
  desayuno: { label: "Desayuno", emoji: "🍳" },
  media_manana: { label: "Media mañana", emoji: "🥤" },
  comida: { label: "Comida", emoji: "🍗" },
  merienda: { label: "Merienda", emoji: "🍓" },
  cena: { label: "Cena", emoji: "🌙" },
  libre: { label: "Libre", emoji: "🎉" },
};

/** A qué momento del día encaja una hora tipo "HH:MM", con los horarios
 * habituales en España (comida a mediodía, cena por la noche). */
export function momentoDesdeHora(hora: string): Momento {
  const h = parseInt(hora.split(":")[0] ?? "", 10);
  if (Number.isNaN(h)) return "comida";
  if (h < 11) return "desayuno";
  if (h < 13) return "media_manana";
  if (h < 17) return "comida";
  if (h < 20) return "merienda";
  return "cena";
}

export const MEAL_PLAN: DayPlan[] = [
  {
    day: "lunes",
    entreno: true,
    diaLibreDieta: false,
    meals: [
      {
        id: "lun-desayuno",
        nombre: "Café con leche + tostada de pan integral con aguacate y huevo",
        kcal: 400,
        proteina: 24,
        ingredientes: ["café", "leche desnatada", "pan integral", "aguacate", "huevos"],
        momento: "desayuno",
      },
      {
        id: "lun-media",
        nombre: "Batido de proteína, plátano y crema de cacahuete",
        kcal: 260,
        proteina: 33,
        ingredientes: ["proteína whey", "leche desnatada", "plátano", "crema de cacahuete"],
        momento: "media_manana",
      },
      {
        id: "lun-comida",
        nombre: "Lentejas estofadas con pollo, chorizo magro y verduras",
        kcal: 660,
        proteina: 52,
        ingredientes: [
          "lentejas",
          "pechuga de pollo",
          "chorizo magro",
          "zanahoria",
          "cebolla",
          "pimiento",
          "ajo",
          "aceite de oliva",
        ],
        momento: "comida",
      },
      {
        id: "lun-merienda",
        nombre: "Yogur griego 0% con nueces, miel y canela",
        kcal: 220,
        proteina: 20,
        ingredientes: ["yogur griego 0%", "nueces", "miel", "canela"],
        momento: "merienda",
      },
      {
        id: "lun-cena",
        nombre: "Salmón al horno con mostaza y eneldo, boniato asado y ensalada de rúcula",
        kcal: 560,
        proteina: 41,
        ingredientes: ["salmón", "mostaza", "eneldo", "boniato", "rúcula", "tomate cherry"],
        momento: "cena",
      },
    ],
  },
  {
    day: "martes",
    entreno: true,
    diaLibreDieta: false,
    meals: [
      {
        id: "mar-desayuno",
        nombre: "Café + yogur griego con avena y plátano",
        kcal: 380,
        proteina: 26,
        ingredientes: ["café", "yogur griego 0%", "avena", "plátano"],
        momento: "desayuno",
      },
      {
        id: "mar-media",
        nombre: "2 huevos duros con especias cajún + manzana",
        kcal: 260,
        proteina: 18,
        ingredientes: ["huevos", "especias cajún", "manzana"],
        momento: "media_manana",
      },
      {
        id: "mar-comida",
        nombre: "Alubias blancas estofadas con pavo y pimentón",
        kcal: 640,
        proteina: 50,
        ingredientes: [
          "alubias blancas",
          "pechuga de pavo",
          "pimentón",
          "cebolla",
          "pimiento",
          "tomate",
          "aceite de oliva",
        ],
        momento: "comida",
      },
      {
        id: "mar-merienda",
        nombre: "Batido de proteína de chocolate con crema de cacahuete y canela",
        kcal: 310,
        proteina: 33,
        ingredientes: ["proteína whey de chocolate", "leche de almendras", "crema de cacahuete", "canela"],
        momento: "merienda",
      },
      {
        id: "mar-cena",
        nombre: "Revuelto de claras con atún, espárragos y tomate seco, tostada integral",
        kcal: 490,
        proteina: 49,
        ingredientes: [
          "claras de huevo pasteurizadas",
          "atún al natural",
          "espárragos",
          "tomate seco",
          "pan integral",
        ],
        momento: "cena",
      },
    ],
  },
  {
    day: "miercoles",
    entreno: false,
    diaLibreDieta: false,
    meals: [
      {
        id: "mie-desayuno",
        nombre: "Café con leche + skyr con muesli sin azúcar y fresas",
        kcal: 370,
        proteina: 27,
        ingredientes: ["café", "leche desnatada", "skyr o queso batido 0%", "muesli sin azúcar", "fresas"],
        momento: "desayuno",
      },
      {
        id: "mie-media",
        nombre: "Batido de proteína con frutos secos y canela",
        kcal: 300,
        proteina: 30,
        ingredientes: ["proteína whey", "leche desnatada", "almendras", "canela"],
        momento: "media_manana",
      },
      {
        id: "mie-comida",
        nombre: "Potaje de garbanzos con bacalao y espinacas",
        kcal: 600,
        proteina: 44,
        ingredientes: ["garbanzos cocidos", "bacalao", "espinacas", "patata", "ajo", "pimentón", "aceite de oliva"],
        momento: "comida",
      },
      {
        id: "mie-merienda",
        nombre: "Requesón con canela, nueces y unas gotas de miel",
        kcal: 230,
        proteina: 22,
        ingredientes: ["requesón", "canela", "nueces", "miel"],
        momento: "merienda",
      },
      {
        id: "mie-cena",
        nombre: "Pavo a la plancha con crema de calabacín y parmesano",
        kcal: 470,
        proteina: 43,
        ingredientes: ["pechuga de pavo", "calabacín", "cebolla", "queso parmesano", "caldo de verduras"],
        momento: "cena",
      },
    ],
  },
  {
    day: "jueves",
    entreno: true,
    diaLibreDieta: false,
    meals: [
      {
        id: "jue-desayuno",
        nombre: "Café + tostada con queso fresco, pavo y tomate",
        kcal: 380,
        proteina: 28,
        ingredientes: ["café", "pan integral", "queso fresco batido 0%", "pechuga de pavo", "tomate"],
        momento: "desayuno",
      },
      {
        id: "jue-media",
        nombre: "Batido de proteína con plátano y un toque de café",
        kcal: 290,
        proteina: 34,
        ingredientes: ["proteína whey", "leche desnatada", "plátano", "café soluble"],
        momento: "media_manana",
      },
      {
        id: "jue-comida",
        nombre: "Guisantes estofados con jamón, zanahoria y huevo poché",
        kcal: 620,
        proteina: 44,
        ingredientes: ["guisantes", "jamón serrano", "zanahoria", "cebolla", "huevos", "patata"],
        momento: "comida",
      },
      {
        id: "jue-merienda",
        nombre: "Yogur griego con proteína, canela y trocitos de manzana",
        kcal: 240,
        proteina: 28,
        ingredientes: ["yogur griego 0%", "proteína whey", "canela", "manzana"],
        momento: "merienda",
      },
      {
        id: "jue-cena",
        nombre: "Solomillo de cerdo al romero con puré de coliflor y ajo asado",
        kcal: 530,
        proteina: 47,
        ingredientes: ["solomillo de cerdo", "romero", "coliflor", "ajo", "aceite de oliva"],
        momento: "cena",
      },
    ],
  },
  {
    day: "viernes",
    entreno: true,
    diaLibreDieta: false,
    meals: [
      {
        id: "vie-desayuno",
        nombre: "Café con leche + yogur griego con avena, cacao puro y plátano",
        kcal: 390,
        proteina: 25,
        ingredientes: ["café", "leche desnatada", "yogur griego 0%", "avena", "cacao puro", "plátano"],
        momento: "desayuno",
      },
      {
        id: "vie-media",
        nombre: "2 huevos duros con tomate, orégano y aceite de oliva",
        kcal: 230,
        proteina: 16,
        ingredientes: ["huevos", "tomate", "orégano", "aceite de oliva"],
        momento: "media_manana",
      },
      {
        id: "vie-comida",
        nombre: "Puchero de garbanzos con pollo, chorizo magro y verduras",
        kcal: 670,
        proteina: 53,
        ingredientes: ["garbanzos cocidos", "pechuga de pollo", "chorizo magro", "patata", "zanahoria", "repollo"],
        momento: "comida",
      },
      {
        id: "vie-merienda",
        nombre: "Batido de proteína con leche desnatada y una pizca de canela",
        kcal: 260,
        proteina: 32,
        ingredientes: ["proteína whey", "leche desnatada", "canela"],
        momento: "merienda",
      },
      {
        id: "vie-cena",
        nombre: "Pollo a la plancha con especias marroquíes y ensalada de garbanzos, pepino y menta",
        kcal: 550,
        proteina: 47,
        ingredientes: [
          "pechuga de pollo",
          "especias marroquíes (ras el hanout)",
          "garbanzos cocidos",
          "pepino",
          "menta",
          "limón",
        ],
        momento: "cena",
      },
    ],
  },
  {
    day: "sabado",
    entreno: false,
    diaLibreDieta: false,
    meals: [
      {
        id: "sab-desayuno",
        nombre: "Café + tostada con huevos revueltos y aguacate",
        kcal: 400,
        proteina: 22,
        ingredientes: ["café", "pan integral", "huevos", "aguacate"],
        momento: "desayuno",
      },
      {
        id: "sab-media",
        nombre: "Batido de proteína con fruta y un toque de jengibre",
        kcal: 290,
        proteina: 32,
        ingredientes: ["proteína whey", "leche desnatada", "manzana", "jengibre"],
        momento: "media_manana",
      },
      {
        id: "sab-comida",
        nombre: "Arroz meloso con pollo, verduras y un toque de azafrán",
        kcal: 630,
        proteina: 46,
        ingredientes: ["arroz", "pechuga de pollo", "pimiento", "judías verdes", "tomate", "ajo", "azafrán"],
        momento: "comida",
      },
      {
        id: "sab-merienda",
        nombre: "Yogur griego con miel, nueces y un poco de granola",
        kcal: 260,
        proteina: 21,
        ingredientes: ["yogur griego 0%", "miel", "nueces", "muesli sin azúcar"],
        momento: "merienda",
      },
      {
        id: "sab-cena",
        nombre: "Tortilla de patata ligera al horno con cebolla caramelizada y ensalada verde",
        kcal: 490,
        proteina: 31,
        ingredientes: ["huevos", "patata", "cebolla", "lechuga", "tomate"],
        momento: "cena",
      },
    ],
  },
  {
    day: "domingo",
    entreno: false,
    diaLibreDieta: true,
    meals: [
      {
        id: "dom-desayuno",
        nombre: "Café + desayuno proteico habitual (mantén esta comida fija)",
        kcal: 420,
        proteina: 35,
        ingredientes: ["café", "huevos", "avena", "proteína whey"],
        momento: "desayuno",
      },
      {
        id: "dom-libre",
        nombre: "Comidas libres del día — disfruta sin contar de forma estricta",
        kcal: 0,
        proteina: 0,
        ingredientes: [],
        momento: "libre",
      },
    ],
  },
];

// Split de 4 días: dos grupos musculares grandes por sesión, dejando la
// última sesión de la semana entera para piernas.
export const WORKOUT_PLAN: WorkoutDay[] = [
  {
    day: "lunes",
    titulo: "Pecho + Tríceps",
    ejercicios: [
      {
        id: "lun-1",
        nombre: "Press banca (barra o mancuernas)",
        pauta: "4 x 8-10",
        emoji: "🏋️",
        comoHacerlo: "Espalda pegada al banco, baja la barra controlada hasta rozar el pecho y empuja sin bloquear los codos de golpe.",
      },
      {
        id: "lun-2",
        nombre: "Press inclinado con mancuernas",
        pauta: "3 x 10",
        emoji: "🏋️",
        comoHacerlo: "Banco a 30-45°, baja las mancuernas a la altura del pecho superior y empuja sin chocarlas arriba.",
      },
      {
        id: "lun-3",
        nombre: "Aperturas con mancuernas o cruces en polea",
        pauta: "3 x 12",
        emoji: "🤲",
        comoHacerlo: "Codos ligeramente flexionados y fijos, abre los brazos en arco hasta sentir el estiramiento en el pecho.",
      },
      {
        id: "lun-4",
        nombre: "Fondos en paralelas (énfasis tríceps)",
        pauta: "3 x 10-12",
        emoji: "🤸",
        comoHacerlo: "Mantén el torso vertical para cargar más el tríceps, baja hasta 90° de codo y empuja fuerte.",
      },
      {
        id: "lun-5",
        nombre: "Extensión de tríceps en polea",
        pauta: "3 x 12",
        emoji: "🦾",
        comoHacerlo: "Codos pegados al cuerpo, extiende hacia abajo solo con el antebrazo, sin mover el hombro.",
      },
      {
        id: "lun-6",
        nombre: "Press francés con barra o mancuerna",
        pauta: "3 x 12",
        emoji: "💪",
        comoHacerlo: "Tumbado, baja el peso hacia la frente flexionando solo el codo, manteniendo los brazos fijos y verticales.",
      },
    ],
  },
  {
    day: "martes",
    titulo: "Espalda + Bíceps",
    ejercicios: [
      {
        id: "mar-1",
        nombre: "Dominadas o jalón al pecho",
        pauta: "4 x 8-10",
        emoji: "🧗",
        comoHacerlo: "Tira llevando el pecho hacia la barra, juntando los omóplatos, y baja controlando hasta extender casi del todo.",
      },
      {
        id: "mar-2",
        nombre: "Remo con barra",
        pauta: "4 x 10",
        emoji: "🚣",
        comoHacerlo: "Espalda recta e inclinada hacia delante, tira del peso hacia el abdomen apretando la espalda arriba.",
      },
      {
        id: "mar-3",
        nombre: "Remo en polea baja",
        pauta: "3 x 12",
        emoji: "🎣",
        comoHacerlo: "Tira con la espalda, no con los brazos: lleva los codos atrás y junta los omóplatos al final del movimiento.",
      },
      {
        id: "mar-4",
        nombre: "Pull-over con mancuerna o en polea",
        pauta: "3 x 12",
        emoji: "🌊",
        comoHacerlo: "Brazos casi rectos, lleva el peso desde detrás de la cabeza hasta encima del pecho sintiendo el dorsal.",
      },
      {
        id: "mar-5",
        nombre: "Curl de bíceps con barra",
        pauta: "3 x 12",
        emoji: "💪",
        comoHacerlo: "Codos fijos pegados al torso, sube el peso solo flexionando el codo, sin balancear el cuerpo.",
      },
      {
        id: "mar-6",
        nombre: "Curl martillo con mancuernas",
        pauta: "3 x 12",
        emoji: "🔨",
        comoHacerlo: "Agarre neutro (palmas mirándose), flexiona sin girar la muñeca para cargar también el antebrazo.",
      },
    ],
  },
  {
    day: "jueves",
    titulo: "Hombro + Abdomen",
    ejercicios: [
      {
        id: "jue-1",
        nombre: "Press militar con mancuernas",
        pauta: "4 x 10",
        emoji: "💪",
        comoHacerlo: "De pie o sentado, empuja las mancuernas hacia arriba sin arquear la espalda, codos ligeramente por delante del cuerpo.",
      },
      {
        id: "jue-2",
        nombre: "Elevaciones laterales",
        pauta: "4 x 15",
        emoji: "🙆",
        comoHacerlo: "Sube los brazos ligeramente flexionados hasta la altura del hombro, sin impulso, controlando la bajada.",
      },
      {
        id: "jue-3",
        nombre: "Pájaros / elevaciones posteriores",
        pauta: "3 x 15",
        emoji: "🐦",
        comoHacerlo: "Inclinado hacia delante, abre los brazos hacia los lados apretando la parte trasera del hombro.",
      },
      {
        id: "jue-4",
        nombre: "Face pull",
        pauta: "3 x 15",
        emoji: "🎯",
        comoHacerlo: "Tira de la cuerda hacia la cara separando las manos, codos altos, apretando la parte trasera del hombro.",
      },
      {
        id: "jue-5",
        nombre: "Plancha abdominal",
        pauta: "3 x 40 seg",
        emoji: "🧘",
        comoHacerlo: "Cuerpo en línea recta de cabeza a talones, abdomen apretado, sin dejar caer la cadera.",
      },
      {
        id: "jue-6",
        nombre: "Elevación de piernas colgado / crunch",
        pauta: "3 x 15",
        emoji: "🌀",
        comoHacerlo: "Sube las piernas con control usando el abdomen, evitando balancearte con el impulso.",
      },
    ],
  },
  {
    day: "viernes",
    titulo: "Piernas",
    ejercicios: [
      {
        id: "vie-1",
        nombre: "Sentadilla con barra",
        pauta: "4 x 8-10",
        emoji: "🏋️",
        comoHacerlo: "Baja como si te sentaras, rodillas en línea con los pies, pecho arriba, hasta que las caderas bajen de las rodillas.",
      },
      {
        id: "vie-2",
        nombre: "Peso muerto rumano",
        pauta: "3 x 10",
        emoji: "🏋️",
        comoHacerlo: "Piernas casi rectas, baja la barra pegada a las piernas empujando la cadera hacia atrás, espalda siempre recta.",
      },
      {
        id: "vie-3",
        nombre: "Zancadas con mancuernas",
        pauta: "3 x 12 por pierna",
        emoji: "🚶",
        comoHacerlo: "Da un paso largo y baja hasta que ambas rodillas queden casi a 90°, sin que la rodilla delantera sobrepase el pie.",
      },
      {
        id: "vie-4",
        nombre: "Prensa de piernas",
        pauta: "3 x 12",
        emoji: "🦵",
        comoHacerlo: "Baja controlado hasta 90° de rodilla, sin despegar la zona lumbar del respaldo.",
      },
      {
        id: "vie-5",
        nombre: "Curl femoral en máquina",
        pauta: "3 x 12",
        emoji: "🦿",
        comoHacerlo: "Flexiona la rodilla llevando el talón hacia el glúteo, sin despegar la cadera del banco.",
      },
      {
        id: "vie-6",
        nombre: "Elevación de talones (gemelos)",
        pauta: "4 x 15",
        emoji: "🦶",
        comoHacerlo: "Sube todo lo que puedas sobre la punta del pie y baja despacio estirando bien el gemelo.",
      },
    ],
  },
];

// Índice plano id → {nombre, emoji} de todos los ejercicios del plan, para
// poder identificarlos en el histórico de registros sin importar qué día
// de la semana era cuando se registraron.
export const EXERCISE_INDEX: Record<string, { nombre: string; emoji: string }> = Object.fromEntries(
  WORKOUT_PLAN.flatMap((dia) => dia.ejercicios.map((ej) => [ej.id, { nombre: ej.nombre, emoji: ej.emoji }]))
);

export const SHOPPING_CATEGORIES = [
  "Proteínas",
  "Lácteos",
  "Legumbres",
  "Carbohidratos",
  "Verduras y fruta",
  "Frutos secos y grasas",
  "Suplementos",
  "Otros",
];

export const CATEGORY_EMOJI: Record<string, string> = {
  "Proteínas": "🍗",
  "Lácteos": "🥛",
  "Legumbres": "🫘",
  "Carbohidratos": "🌾",
  "Verduras y fruta": "🥦",
  "Frutos secos y grasas": "🥜",
  "Suplementos": "💊",
  "Otros": "🧂",
};

function item(id: string, nombre: string, categoria: string): ShoppingItem {
  return { id, nombre, categoria, base: true };
}

export const BASE_SHOPPING_LIST: ShoppingItem[] = [
  item("p-pollo", "Pechuga de pollo", "Proteínas"),
  item("p-pavo", "Pechuga de pavo", "Proteínas"),
  item("p-ternera", "Ternera magra", "Proteínas"),
  item("p-cerdo", "Solomillo de cerdo", "Proteínas"),
  item("p-salmon", "Salmón", "Proteínas"),
  item("p-merluza", "Merluza", "Proteínas"),
  item("p-atun", "Atún al natural (lata)", "Proteínas"),
  item("p-huevos", "Huevos", "Proteínas"),
  item("p-claras", "Claras de huevo pasteurizadas", "Proteínas"),
  item("p-chorizo", "Chorizo magro", "Proteínas"),
  item("p-bacalao", "Bacalao", "Proteínas"),
  item("p-jamonserrano", "Jamón serrano", "Proteínas"),
  item("l-yogur", "Yogur griego 0%", "Lácteos"),
  item("l-skyr", "Skyr o queso batido 0%", "Lácteos"),
  item("l-requeson", "Requesón", "Lácteos"),
  item("l-leche", "Leche desnatada", "Lácteos"),
  item("l-quesofresco", "Queso fresco batido 0%", "Lácteos"),
  item("l-feta", "Queso feta", "Lácteos"),
  item("l-parmesano", "Queso parmesano", "Lácteos"),
  item("leg-lentejas", "Lentejas", "Legumbres"),
  item("leg-alubias", "Alubias blancas", "Legumbres"),
  item("leg-garbanzos", "Garbanzos cocidos", "Legumbres"),
  item("leg-guisantes", "Guisantes", "Legumbres"),
  item("c-avena", "Avena", "Carbohidratos"),
  item("c-arroz", "Arroz", "Carbohidratos"),
  item("c-arrozintegral", "Arroz integral", "Carbohidratos"),
  item("c-arrozbasmati", "Arroz basmati", "Carbohidratos"),
  item("c-quinoa", "Quinoa", "Carbohidratos"),
  item("c-patata", "Patata", "Carbohidratos"),
  item("c-boniato", "Boniato", "Carbohidratos"),
  item("c-panintegral", "Pan integral", "Carbohidratos"),
  item("c-pastaintegral", "Pasta integral", "Carbohidratos"),
  item("c-muesli", "Muesli sin azúcar", "Carbohidratos"),
  item("v-espinacas", "Espinacas", "Verduras y fruta"),
  item("v-brocoli", "Brócoli", "Verduras y fruta"),
  item("v-pimiento", "Pimiento", "Verduras y fruta"),
  item("v-cebolla", "Cebolla", "Verduras y fruta"),
  item("v-esparragos", "Espárragos", "Verduras y fruta"),
  item("v-calabacin", "Calabacín", "Verduras y fruta"),
  item("v-judiasverdes", "Judías verdes", "Verduras y fruta"),
  item("v-coliflor", "Coliflor", "Verduras y fruta"),
  item("v-tomate", "Tomate", "Verduras y fruta"),
  item("v-tomatecherry", "Tomate cherry", "Verduras y fruta"),
  item("v-tomateseco", "Tomate seco", "Verduras y fruta"),
  item("v-lechuga", "Lechuga", "Verduras y fruta"),
  item("v-rucula", "Rúcula", "Verduras y fruta"),
  item("v-pepino", "Pepino", "Verduras y fruta"),
  item("v-aguacate", "Aguacate", "Verduras y fruta"),
  item("v-platano", "Plátano", "Verduras y fruta"),
  item("v-arandanos", "Arándanos", "Verduras y fruta"),
  item("v-fresas", "Fresas", "Verduras y fruta"),
  item("v-manzana", "Manzana", "Verduras y fruta"),
  item("v-limon", "Limón", "Verduras y fruta"),
  item("v-menta", "Menta", "Verduras y fruta"),
  item("v-zanahoria", "Zanahoria", "Verduras y fruta"),
  item("v-repollo", "Repollo", "Verduras y fruta"),
  item("f-nueces", "Nueces", "Frutos secos y grasas"),
  item("f-almendras", "Almendras", "Frutos secos y grasas"),
  item("f-avellanas", "Avellanas", "Frutos secos y grasas"),
  item("f-cacahuete", "Crema de cacahuete 100%", "Frutos secos y grasas"),
  item("f-aceite", "Aceite de oliva virgen extra", "Frutos secos y grasas"),
  item("f-sesamo", "Semillas de sésamo", "Frutos secos y grasas"),
  item("f-aceitesesamo", "Aceite de sésamo", "Frutos secos y grasas"),
  item("s-whey", "Proteína whey", "Suplementos"),
  item("s-creatina", "Creatina monohidrato", "Suplementos"),
  item("s-betaalanina", "Beta-alanina", "Suplementos"),
  item("o-miel", "Miel", "Otros"),
  item("o-canela", "Canela", "Otros"),
  item("o-cacao", "Cacao puro en polvo", "Otros"),
  item("o-curryrojo", "Pasta de curry rojo", "Otros"),
  item("o-cocoleche", "Leche de coco light", "Otros"),
  item("o-teriyaki", "Salsa teriyaki baja en azúcar", "Otros"),
  item("o-soja", "Salsa de soja baja en sal", "Otros"),
  item("o-pesto", "Pesto ligero", "Otros"),
  item("o-marroquies", "Especias marroquíes (ras el hanout)", "Otros"),
  item("o-cajun", "Especias cajún", "Otros"),
  item("o-jengibre", "Jengibre", "Otros"),
  item("o-romero", "Romero", "Otros"),
  item("o-eneldo", "Eneldo", "Otros"),
  item("o-mostaza", "Mostaza", "Otros"),
  item("o-ajo", "Ajo", "Otros"),
  item("o-cafesoluble", "Café soluble", "Otros"),
  item("o-caldoverduras", "Caldo de verduras", "Otros"),
  item("o-vainilla", "Extracto de vainilla", "Otros"),
  item("o-provenzales", "Hierbas provenzales", "Otros"),
  item("o-oregano", "Orégano", "Otros"),
  item("o-sidra", "Sidra o vino blanco", "Otros"),
  item("o-pimenton", "Pimentón", "Otros"),
  item("o-azafran", "Azafrán", "Otros"),
];
